name: ruth
description: Ruth - A Cross platform Midi Piano built with Flutter.
version: 1.7.0+410
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  recase: ^4.1.0
  shared_preferences: ^2.5.4
  audioplayers: ^6.6.0
  intl: any
  country_flags: ^3.2.0
  google_fonts: ^6.2.1
  hugeicons: ^1.1.5

dependency_overrides:
  win32: ^5.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/sounds/shot/
    - assets/sounds/sustain/
    - CHANGELOG.md
